<?php View::process($page_module, $page_title, $set_title); ?>

<section class="content mkc-shell-view">
    <?php View::notify(); ?>

    <div class="box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title"><?php echo $page_title; ?></h3>
        </div>
    <div class="box-body">
    <?php echo MkcForm::open('', 'post', array('id'=>'form', 'class'=>'mkc-validate')); ?>

        <div class="row form-group">
            <div class="col-md-6">
                <?php echo MkcForm::text('backup.denominacion', array('class'=>'form-control input-xxlarge input-required input-alphanum mask-alphanum show-error'), NULL, 'Denominación'); ?>
            </div>
        </div>
    </div>
        <div class="box-footer">
        <div class="row-fluid">
            <div class="col-xs-12 form-group form-actions text-right">
                <?php echo MkcButton::save('Crear copia de seguridad'); ?>
                <?php echo MkcButton::reset('form'); ?>
                <?php echo MkcButton::cancel(); ?>
            </div>
        </div>
        </div>

    <?php echo MkcForm::close(); ?>

</div>
</section>