<?php View::notify(); ?>

<div class="container-fluid mkc-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo MkcForm::open('', 'post', array('id'=>'form', 'class'=>'mkc-validate')); ?>

        <div class="row-fluid">
            <div class="span6">
                <?php echo MkcForm::text('backup.denominacion', array('class'=>'input-xxlarge input-required input-alphanum mask-alphanum show-error'), NULL, 'Denominación'); ?>
            </div>
        </div>

        <div class="row-fluid">
            <div class="form-actions">
                <?php echo MkcButton::save('Crear copia de seguridad'); ?>
                <?php echo MkcButton::reset('form'); ?>
                <?php echo MkcButton::cancel(); ?>
            </div>
        </div>

    <?php echo MkcForm::close(); ?>

</div>