<?php View::process($page_module, $page_title, $set_title); ?>
<section class="content">
    <div class="mkc-shell-view">
        <?php View::notify(); ?>
        <div class="box box-primary">
            <div class="box-header">
                <h3 class="box-title col-xs-6">
                    <?php echo $page_title; ?>
                </h3>
        <div class="btn-actions col-xs-6 text-right">
            <?php echo MkcButton::report("auditoria/listar/$fecha/", 'html', 'Reporte de auditorías', 'imprimir'); ?>
        </div>
    </div>
    <div class="box-body">
    <div class="mkc-overflow">

        <table class="table table-bordered table-hover table-striped table-condensed">
            <thead>
                <tr>
                    <th class="no-responsive mkc-text-middle" style="width: 15px;">NUM</th>
                    <th class="no-responsive mkc-text-middle">FECHA</th>
                    <th class="no-responsive mkc-text-middle">TIPO</th>
                    <th class="no-responsive mkc-text-middle">USUARIO</th>
                    <th class="no-responsive mkc-text-middle">IP</th>
                    <th class="no-responsive mkc-text-center">DESCRIPCION</th>
                </tr>
            </thead>
            <tbody>
                <?php if($audits->items) { ?>
                    <?php foreach($audits->items as $audit): ?>
                    <tr>
                        <td><?php echo $audits->counter; ?></td>
                        <td><?php echo $audit['fecha']; ?></td>
                        <td>
                            <?php if($audit['tipo'] == 'ERROR' OR $audit['tipo'] == 'ALERT') { ?>
                                <span class="label label-important"><?php echo $audit['tipo']; ?></span>
                            <?php } else if($audit['tipo'] == 'WARNING' OR $audit['tipo'] == 'CRITICAL' OR $audit['tipo'] == 'EMERGENCE') { ?>
                                <span class="label label-warning"><?php echo $audit['tipo']; ?></span>
                            <?php } else if($audit['tipo'] == 'NOTICE' OR $audit['tipo'] == 'INFO') { ?>
                                <span class="label label-info"><?php echo $audit['tipo']; ?></span>
                            <?php } else { ?>
                                <span class="label"><?php echo $audit['tipo']; ?></span>
                            <?php } ?>
                        </td>
                        <td><?php echo $audit['usuario']; ?></td>
                        <td><?php echo $audit['ip']; ?></td>
                        <td><?php echo $audit['descripcion']; ?></td>
                    </tr>
                    <?php $audits->counter++; ?>
                    <?php endforeach; ?>
                <?php } ?>
            </tbody>

        </table>

    </div>
    </div>
    <div class="box-footer">
    <?php View::partial('paginators/default', false, array('page'=>$audits, 'url'=>"sistema/sucesos/listar/$fecha/")); ?>

</div>
</div>
</div>
</section>