<?php View::notify(); ?>

<div class="container-fluid mkc-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo MkcForm::open('', 'post', array('id'=>'form', 'class'=>'mkc-validate')); ?>

        <div class="row-fluid">
            <div class="col-xs-6">
                <?php echo MkcForm::date('log', array('class'=>'input-required mask-date input-date show-errors'), date("Y-m-d"), 'Día'); ?>
            </div>
        </div>

        <div class="row-fluid">
            <div class="form-actions">
                <?php echo MkcButton::submit('Listar logs', 'check', NULL, 'mostrar'); ?>
                <?php echo MkcButton::cancel(); ?>
            </div>
        </div>


    <?php echo MkcForm::close(); ?>


</div>