<?php View::process($page_module, $page_title, $set_title); ?>

<section class="content mkc-shell-view">
    <?php View::notify(); ?>

    <div class="box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title"><?php echo $page_title; ?></h3>
        </div>

        <?php echo MkcForm::open('', 'post', array('id'=>'form', 'class'=>'mkc-validate')); ?>
        <div class="box-body">
            <div class="row form-group">
                <div class="col-md-4">
                    <?php echo MkcForm::text('menu.menu', array('class'=>'form-control input-required mask-alphanum show-error'), NULL, 'Título'); ?>
                </div>
                <div class="col-md-4">
                    <?php echo MkcForm::dbSelect('menu.menu_id', 'menu', array('sistema/menu', 'getListadoMenu', Menu::ACTIVO), 'Ninguno', array('class'=>'form-control mask-pint show-errors'), NULL, 'Menú padre'); ?>
                </div>
                <div class="col-md-4">
                    <?php echo MkcForm::dbSelect('menu.recurso_id', 'recurso', array('sistema/recurso', 'getListadoRecurso', Recurso::ACTIVO), 'Ninguno', array('class'=>'form-control mask-pint show-errors'), NULL, 'Recurso'); ?>
                </div>
            </div>
            <div class="row form-group">
                <div class="col-md-4">
                    <?php echo MkcForm::text('menu.posicion', array('class'=>'form-control mask-pint show-error'), NULL, 'Posición'); ?>
                </div>
                <div class="col-md-4">
                    <?php echo MkcForm::text('menu.icono', array('class'=>'form-control mask-alphanum show-error'), NULL, 'Icono a mostrar'); ?>
                </div>
                <div class="col-md-4">
                    <?php echo MkcForm::text('menu.url', array('class'=>'form-control show-error'), NULL, 'URL'); ?>
                </div>
            </div>
            <div class="row form-group">
                <div class="col-md-4">
                    <?php echo MkcForm::select('menu.visibilidad', array(Menu::BACKEND=>'Backend', Menu::FRONTEND=>'Frontend'), array('class'=>'form-control required show-errors'), Menu::BACKEND, 'Visibilidad'); ?>
                </div>
            </div>
        </div>
        <div class="box-footer">
            <div class="row form-group">
                <div class="col-xs-12 form-group form-actions text-right">
                    <?php echo MkcButton::save('Guardar menú'); ?>
                    <?php echo MkcButton::reset('form'); ?>
                    <?php echo MkcButton::cancel('sistema/menu/listar/'); ?>
                </div>
            </div>
        </div>
        <?php echo MkcForm::close(); ?>

    </div>
</section>

    <script type="text/javascript" >
        $(function(){
            $("#menu_recurso_id").on('change',function(){
                var recurso = $('option:selected',this).text();
                $("#menu_url").val(recurso.replace('/*','/'));
            });
        });
    </script>