<?php View::notify(); ?>

<div class="container-fluid mkc-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo MkcForm::open('', 'post', array('id'=>'form', 'class'=>'mkc-validate')); ?>

        <div class="row-fluid">
            <div class="span4">
                <?php echo MkcForm::text('menu.menu', array('class'=>'input-required mask-alphanum show-error'), $menu->menu, 'Título'); ?>
            </div>
            <div class="span4">
                <?php echo MkcForm::dbSelect('menu.menu_id', 'menu', array('sistema/menu', 'getListadoMenu', Menu::ACTIVO), 'Ninguno', array('class'=>'mask-pint show-errors'), $menu->menu_id, 'Menú padre'); ?>
            </div>
            <div class="span4">
                <?php echo MkcForm::dbSelect('menu.recurso_id', 'recurso', array('sistema/recurso', 'getListadoRecurso', Recurso::ACTIVO), 'Ninguno', array('class'=>'mask-pint show-errors'), $menu->recurso_id, 'Recurso'); ?>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span4">
                <?php echo MkcForm::text('menu.posicion', array('class'=>'mask-pint show-error'), $menu->posicion, 'Posición'); ?>
            </div>
            <div class="span4">
                <?php echo MkcForm::text('menu.icono', array('class'=>'mask-alphanum show-error'), $menu->icono, 'Icono a mostrar'); ?>
            </div>
            <div class="span4">
                <?php echo MkcForm::text('menu.url', array('class'=>'show-error'), $menu->url, 'URL'); ?>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span4">
                <?php echo MkcForm::select('menu.visibilidad', array(Menu::BACKEND=>'Backend', Menu::FRONTEND=>'Frontend'), array('class'=>'input-required show-errors'), $menu->visibilidad, 'Visibilidad'); ?>
            </div>
            <?php echo MkcForm::hiddenKey('menu.id', $menu->id)?>
        </div>

        <div class="row-fluid">
            <div class="form-actions">
                <?php echo MkcButton::save('Guardar menu'); ?>
                <?php echo MkcButton::reset('form'); ?>
                <?php echo MkcButton::cancel('sistema/menu/listar/'); ?>
            </div>
        </div>

    <?php echo MkcForm::close(); ?>

</div>
