<?php View::process($page_module, $page_title, $set_title); ?>
<section class="content">
    <div class="mkc-shell-view">
        <?php View::notify(); ?>
        <div class="box box-primary">
            <div class="box-header">
                <h3 class="box-title col-xs-6">
                    <?php echo $page_title; ?>
                </h3>

                <div class="btn-actions col-xs-6 text-right">
                    <?php echo MkcHtml::button("sistema/menu/agregar/", 'agregar', array('class'=>'btn-success'), 'check', APP_AJAX); ?>
                </div>
            </div>
            <div class="box-body">
                <div class="mkc-overflow">
                    <table id="table" class="table table-bordered table-hover table-striped table-condensed table-responsive">
                        <thead>
                            <tr>
                                <th class="col-collapse">NUM</th>
                                <th class="col-collapse">POSICION</th>
                                <th class="col-collapse">PADRE</th>
                                <th class="col-collapse">TITULO</th>
                                <th class="col-collapse">RECURSO</th>
                                <th class="col-collapse">URL</th>
                                <th class="col-collapse">ICONO</th>
                                <th class="col-collapse">VISIBILIDAD</th>
                                <th class="col-collapse">ESTADO</th>
                                <th class="col-collapse">ACCIONES</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach($menus->items as $menu): ?>
                                <?php if(!APP_OFFICE && $menu->id == Menu::SUCURSAL) { ?>
                                    <?php continue; ?>
                                    <?php } ?>
                                    <?php $key_upd = MkcSecurity::getKey($menu->id, 'upd_menu'); ?>
                                    <?php $key_ina = MkcSecurity::getKey($menu->id, 'inactivar_menu'); ?>
                                    <?php $key_rea = MkcSecurity::getKey($menu->id, 'reactivar_menu'); ?>
                                    <?php $key_del = MkcSecurity::getKey($menu->id, 'eliminar_menu'); ?>
                                    <tr>
                                        <td><?php echo $menus->counter; ?></td>
                                        <td><?php echo $menu->posicion; ?></td>
                                        <td><?php echo $menu->padre; ?></td>
                                        <td><?php echo $menu->menu; ?></td>
                                        <td><?php echo $menu->recurso; ?></td>
                                        <td><?php echo $menu->url; ?></td>
                                        <td><?php echo $menu->icono; ?></td>
                                        <td><?php echo ($menu->visibilidad == Menu::BACKEND) ? '<span class="label label-success">Backend</span>' : '<span class="label label-warning">Frontend</span>'; ; ?></td>
                                        <td><?php echo ($menu->activo == Menu::ACTIVO) ? '<span class="label label-success">Activo</span>' : '<span class="label label-important">Bloqueado</span>'; ; ?></td>
                                        <td>
                                            <?php echo MkcHtml::buttonTable('Modificar menú', "sistema/menu/editar/$key_upd/", null, 'info', 'edit'); ?>
                                            <?php if($menu->activo == Menu::ACTIVO) { ?>
                                                <?php echo MkcHtml::buttonTable('Bloquear menú', "sistema/menu/estado/inactivar/$key_ina/", null, 'success', 'flag'); ?>
                                                <?php } else { ?>
                                                <?php echo MkcHtml::buttonTable('Reactivar menú', "sistema/menu/estado/reactivar/$key_rea/", null, 'danger', 'flag'); ?>
                                                <?php } ?>
                                                <?php echo MkcHtml::buttonTable('Eliminar menú', "sistema/menu/eliminar/$key_del/", array('class'=>'js-confirm', 'confirm-title'=>'Eliminar menú', 'confirm-body'=>'Está seguro de eliminar este menú? <br />Recuerda que esta operación no se puede reversar.'), 'danger', 'trash'); ?>
                                            </td>
                                        </tr>
                                        <?php $menus->counter++; ?>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="box-footer">
                        <?php View::partial('paginators/default', false, array('page'=>$menus, 'url'=>"sistema/menu/listar/$order/")); ?>
                    </div>
                </div>
            </div>
        </section>