<?php View::process($page_module, $page_title, $set_title); ?>
<section class="content mkc-shell-view">
    <?php View::notify(); ?>
    <div class="box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title"><?php echo $page_title; ?></h3>
        </div>
        <div class="box-body">
            <?php if(DESKTOP) { ?>
            <ul class="nav nav-tabs">
                <?php } else { ?>
                <ul class="nav nav-pills nav-stacked">
                    <?php } ?>
                    <li class="active"><a href="#tab1" data-toggle="tab">Información del perfil</a></li>
                    <li><a href="#tab2" data-toggle="tab">Usuarios asignados</a></li>
                </ul>
                <div class="tab-content">
                    <div class="tab-pane active" id="tab1">
                        <?php echo MkcForm::open(); ?>
                        <div class="row-fluid">
                            <div class="col-md-4">
                                <?php echo MkcForm::text('perfil.perfil', NULL, $perfil->perfil, 'Nombre'); ?>
                            </div>
                            <div class="col-md-4">
                                <?php echo MkcForm::text('perfil.perfil', NULL, $perfil->plantilla, 'Plantilla'); ?>
                            </div>
                            <div class="col-md-4">
                                <?php echo MkcForm::text('perfil.perfil', NULL, ($perfil->estado == Perfil::ACTIVO) ? 'ACTIVO' : 'BLOQUEADO', 'Estado'); ?>
                            </div>
                        </div>
                        <?php echo MkcForm::close(); ?>
                    </div>
                    <div class="tab-pane" id="tab2">
                        <?php View::process('Información de usuarios', NULL, FALSE); ?>
                        <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
                            <thead>
                                <tr>
                                    <th>NUM</th>
                                    <th class="col-collapse" data-search="usuario">USUARIO</th>
                                    <th class="col-collapse" data-search="nombre">NOMBRE</th>
                                    <th class="col-collapse" data-search="apellido">APELLIDO</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach($usuarios->items as $usuario): ?>
                                    <tr>
                                        <td><?php echo $usuario->counter; ?></td>
                                        <td><?php echo $usuario->login; ?></td>
                                        <td><?php echo $usuario->nombre; ?></td>
                                        <td><?php echo $usuario->apellido; ?></td>
                                    </tr>
                                    <?php $usuarios->counter++; ?>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </ul>
        </div>
        <div class="box-footer">
            <?php View::partial('paginators/default', false, array('page'=>$usuarios, 'url'=>"sistema/perfil/ver/$key/$order/")); ?>
            <div class="row-fluid">
                <div class="form-actions">
                    <?php echo MkcButton::back('sistema/meu/listar/'); ?>
                </div>
            </div>
        </div>
    </div>
</section>
<script type="text/javascript">
    $(function() {
        $('table').mkcGrid({
            form_search: false,
            order_attr: '<?php echo (APP_AJAX) ? 'class="mkc-ajax mkc-spinner"' : ''; ?>',
            order_action: $.KumbiaPHP.publicPath+"sistema/perfil/ver/<?php echo $key; ?>/"
        });
    });
</script>