<!DOCTYPE html>
<html lang="es">
<head>
    <title><?php echo $page_title; ?></title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta charset="<?php echo APP_CHARSET; ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="robots" content="noindex,nofollow" />
    <?php if(!APP_LOCAL) { ?>        
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <?php } else { ?>
    <?php Tag::css('bootstrap/bootstrap.min') ?>
    <?php Tag::css('font-awesome/font-awesome.min') ?>
    <?php Tag::css('ionicons/ionicons.min') ?>
    <?php } ?>
    <?php Tag::css('bootstrap/datepicker'); ?>
    <?php Tag::css('admin/Admin.min') ?>
    <?php Tag::css('admin/skins/skin-blue.min') ?>
    <?php Tag::css('file-upload'); ?>
    <?php echo Html::includeCss(); ?>
    <?php if(!APP_LOCAL) { ?>
    <link href="http://fonts.googleapis.com/css?family=Play:400,700" rel="stylesheet" type="text/css">
    <?php } ?>
    <style type="text/css">

    </style>
    <?php echo Tag::js('jquery/jquery.min').PHP_EOL; ?>
    <script type="text/javascript">
        function MkcTitle(title) { if($(document).attr('title') != title) { $(document).attr('title', title); } }
    </script>

</head>
<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
        <header class="main-header">
            <!-- Logo -->
            <a href="/dashboard" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini"><b>Wisp</b>C</span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg"><b>Wisp</b>Center</span>
            </a>
            <?php echo View::partial('backend/main-header'); ?>
        </header>
        <aside class="main-sidebar">
            <section class="sidebar">
                <div class="user-panel">
                    <div class="pull-left image">
                        <img src="dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
                    </div>
                    <div class="pull-left info">
                        <p><?php echo Session::get('nombre').' '.Session::get('apellido'); ?></p>
                        <!-- Status -->
                        <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
                    </div>
                </div>
                <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
              <input type="text" name="q" class="form-control" placeholder="Search...">
              <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i></button>
              </span>
            </div>
          </form>
                <?php MkcMenu::load(Menu::BACKEND, Session::get('perfil_id')); ?>

               <?php if(!MOBILE) {?>
                <?php View::partial('backend/main'); ?>
                <?php } ?>
            </section>
        </aside>
        <div class="content-wrapper">
                    <noscript><h5 style="text-align: center;">¡Tu navegador no soporta Javascript!.. Activa el uso de Javascript en tu navegador.</h5><meta http-equiv="refresh" content="1; URL=<?php echo PUBLIC_PATH; ?>sistema/login/salir/no-script/" /></noscript>
                    <?php View::content(); ?>
        </div>
        <footer class="main-footer">
            <?php View::partial('backend/footer'); ?>
        </footer>
        <aside class="control-sidebar control-sidebar-dark">
            <?php echo View::partial('backend/control-sidebar'); ?>
        </aside>
    </div>
<?php echo Tag::js('bootstrap/bootstrap.min').PHP_EOL; ?>
<?php echo Tag::js('bootstrap/bootstrap-datepicker').PHP_EOL; ?>
<?php echo Tag::js('utils/var').PHP_EOL; ?>
<?php echo Tag::js('utils/validador').PHP_EOL; ?>

<?php echo MkcDialog::alert('Se ha producido un error en la validación del formulario.', 'subtext: Verifica los datos e intenta nuevamente.', 'title: Formulario incorrecto', 'name: errorForm'); ?>
<?php if(PRODUCTION) { ?>
<?php echo MkcDialog::alert('Se ha generado la siguiente excepción: <br /><span id="mkc-error-ajax"></span>.', 'title: Oops! hemos realizado algo mal.', 'name: errorAjax'); ?>
<?php } else { ?>
<?php echo MkcDialog::alert('Se ha generado la siguiente excepción: <br /><span id="mkc-error-ajax"></span>.<br /><span id="mkc-info-error-ajax"></span>', 'title: Oops! hemos realizado algo mal.', 'name: errorAjax'); ?>
<?php } ?>
<?php echo MkcDialog::alert('Usted no posee los permisos necesarios para realizar esta acción.', 'title: Acceso denegado', 'name: accessControl'); ?>

</body>
</html>
