<!DOCTYPE html>
<html lang="es">
<head>
    <title><?php echo $page_title; ?></title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta charset="<?php echo APP_CHARSET; ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="robots" content="noindex,nofollow" />
    <?php if(!APP_LOCAL) { ?>        
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <?php } else { ?>
    <?php Tag::css('bootstrap/bootstrap.min') ?>
    <?php Tag::css('font-awesome/font-awesome.min') ?>
    <?php Tag::css('ionicons/ionicons.min') ?>
    <?php } ?>
    <?php Tag::css('admin/Admin.min') ?>
    <?php Tag::css('admin/skins/skin-blue.min') ?>
    <?php echo Html::includeCss(); ?>
    <link rel="stylesheet" href="<?php echo PUBLIC_PATH; ?>plugins/iCheck/square/blue.css">
    <?php echo Tag::js('jquery/jquery.min').PHP_EOL; ?>

</head>
<body class="hold-transition login-page">

    <div class="login-box">
        <div id="mkc-console"></div>
        <div class="login-logo">
            <?php echo Html::link('dashboard/', 'WispCenter') ?>
        </div>
        <div class="login-box-body">
            <?php echo View::content(); ?>
        </div>
    </div>

    <div id="mkc-loading-content" class="alpha60"></div>
    <div id="mkc-spinner" class="preview mkc-corner-all mkc-shadow-dark"></div>

    <script type="text/javascript">
        $(function () {
            jQuery.support.placeholder = false;
            test = document.createElement('input');
            if('placeholder' in test) jQuery.support.placeholder = true;
            if (!$.support.placeholder) {
                $('.field').find ('label').show();
            }
        });
    </script>

    <?php echo Tag::js('bootstrap/bootstrap.min').PHP_EOL; ?>
    <?php echo Tag::js('admin/app.min').PHP_EOL; ?>
    <?php echo Tag::js('jquery/jquery.kumbiaphp').PHP_EOL; ?>
    <?php echo Tag::js('jquery/jquery.keyfilter').PHP_EOL; ?>
    <?php echo Tag::js('jquery/jquery.mkcload').PHP_EOL; ?>
    <?php echo Tag::js('vendors/jsspin.min').PHP_EOL; ?>
    <?php echo Tag::js('jquery/jquery.spin').PHP_EOL; ?>
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
<!--[if lt IE 9]>
<?php echo Tag::js('vendors/html5').PHP_EOL; ?>
<![endif]-->
<?php echo Tag::js('utils/var').PHP_EOL; ?>

<?php echo MkcDialog::alert('Se ha generado la siguiente excepción: <br /><span id="mkc-error-ajax"></span>.', 'title: Oops! hemos realizado algo mal.', 'name: errorAjax'); ?>
<?php echo MkcDialog::alert('Se ha producido un error en la validación del formulario.', 'subtext: Verifica los datos e intenta nuevamente.', 'title: Formulario incorrecto', 'name: errorForm'); ?>

<script src="<?=PUBLIC_PATH; ?>plugins/iCheck/icheck.min.js"></script>
<script>
    $(function () {
        $('input').iCheck({
            checkboxClass: 'icheckbox_square-blue',
            radioClass: 'iradio_square-blue',
            increaseArea: '20%' // optional
        });
    });
</script>
</body>
</html>
