<section class="content-header">
        <?php View::process($page_module, $page_title, $set_title); ?>
    </section>
    <section class="content">
    <div class="mkc-shell-view">
        <?php View::notify(); ?>
        <div class="box box-primary">
        <div class="box-header">
            <h3 class="box-title">
                Lista de Accesos
            </h3>
        </div>
            <div class="box-body">
    <div class="mkc-overflow">

        <table id="table" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>NUM</th>
                    <th class="col-collapse" data-search="fecha">FECHA</th>
                    <th class="col-collapse">HORA</th>
                    <th class="col-collapse" data-search="nombre">NOMBRE</th>
                    <th class="col-collapse" data-search="apellido">APELLIDO</th>
                    <th class="col-collapse" data-search="ip">IP</th>
                    <th class="col-collapse" data-search="tipo_acceso">TIPO ACCESO</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($accesos->items as $acceso): ?>
                    <tr>
                        <td><?php echo $accesos->counter; ?></td>
                        <td><?php echo date("Y-m-d", strtotime($acceso->registrado_at)); ?></td>
                        <td><?php echo date("H:i:s", strtotime($acceso->registrado_at)); ?></td>
                        <td><?php echo $acceso->nombre; ?></td>
                        <td><?php echo $acceso->apellido; ?></td>
                        <td><?php echo $acceso->ip; ?></td>
                        <td><?php echo ($acceso->tipo_acceso == Acceso::ENTRADA) ? '<span class="badge bg-green">Entrada</span>' : '<span class="badge bg-orange">Salida</span>'; ; ?></td>
                    </tr>
                    <?php $accesos->counter++; ?>
                <?php endforeach; ?>
            </tbody>
        </table>

    </div>

                <?php View::partial('paginators/default', false, array('page'=>$acceso, 'url'=>"sistema/acceso/listar/$order/")); ?>
            </div>
        </div>
        </div>
    </section>