<?php View::process($page_module, $page_title, $set_title); ?>

<section class="content mkc-shell-view">
    <?php View::notify(); ?>

    <div class="box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title"><?php echo $page_title; ?></h3>
        </div>

        <?php echo MkcForm::open('', 'post', array('id'=>'form', 'class'=>'form-control mkc-validate', 'role'=>'form')); ?>
        <div class="box-body">
            <div class="row form-group">
                <div class="col-xs-12">
                    <?php echo MkcForm::text('sucursal.sucursal', array('class'=>'form-control input-xxlarge form-control input-required form-control input-alphanum mask-alphanum show-error'), NULL, 'Nombre de la sucursal'); ?>
                </div>
            </div>
            <div class="row form-group">
                <div class="col-xs-6">
                    <?php echo MkcForm::text('sucursal.direccion', array('class'=>'form-control input-xxlarge form-control input-required form-control input-alphanum mask-alphanum show-error'), NULL, 'Dirección'); ?>
                </div>
                <div class="col-xs-6">
                    <?php echo MkcForm::text('ciudad', array('class'=>'form-control input-xxlarge form-control input-required form-control input-alphanum mask-alphanum show-error', 'autocomplete'=>'off'), NULL, 'Ciudad'); ?>
                </div>
            </div>
            <div class="row form-group">
                <div class="col-xs-4">
                    <?php echo MkcForm::tel('sucursal.celular', array('class'=>'form-control input-numeric mask-pint show-error'), NULL, 'Celular'); ?>
                </div>
                <div class="col-xs-4">
                    <?php echo MkcForm::tel('sucursal.telefono', array('class'=>'form-control input-numeric mask-pint show-error'), NULL, 'Teléfono'); ?>
                </div>
                <div class="col-xs-4">
                    <?php echo MkcForm::tel('sucursal.fax', array('class'=>'form-control input-numeric mask-pint show-error'), NULL, 'Fax'); ?>
                </div>
            </div>
        </div>
        <div class="box-footer">
            <div class="row form-group">
                <div class="col-xs-12 form-group form-actions text-right">
                    <?php echo MkcButton::save('Guardar sucursal'); ?>
                    <?php echo MkcButton::reset('form'); ?>
                    <?php echo MkcButton::cancel(); ?>
                </div>
            </div>
        </div>
        <?php echo MkcForm::close(); ?>
    </div>
</section>