<?php View::process($page_module, $page_title, $set_title); ?>
<section class="content">
    <div class="mkc-shell-view">
        <?php View::notify(); ?>
        <div class="box box-primary">
            <div class="box-header">
                <h3 class="box-title col-xs-6">
                    <?php echo $page_title; ?>
                </h3>
                <div class="btn-actions col-xs-6 text-right">
                    <?php echo MkcHtml::button("config/sucursal/agregar/", 'agregar', array('class'=>'btn-success'), 'check', APP_AJAX); ?>
                </div>
            </div>


            <div class="box-body">

                <div class="mkc-overflow">


                    <table id="table" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>NUM</th>
                                <th class="col-collapse" data-search="sucursal">SUCURSAL</th>
                                <th class="col-collapse" data-search="direccion">DIRECCION</th>
                                <th class="col-collapse" data-search="ciudad">CIUDAD</th>
                                <th class="col-collapse" data-search="celular">CELULAR</th>
                                <th class="col-collapse" data-search="telefono">TELEFONO</th>
                                <th class="col-collapse" data-search="fax">FAX</th>
                                <th class="btn-actions no-responsive" style="width: 100px;">ACCIONES</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach($sucursales->items as $sucursal): ?>
                                <?php $key_upd = MkcSecurity::getKey($sucursal->id, 'upd_sucursal'); ?>
                                <?php $key_del = MkcSecurity::getKey($sucursal->id, 'del_sucursal'); ?>
                                <tr>
                                    <td><?php echo $sucursales->counter; ?></td>
                                    <td><?php echo $sucursal->sucursal; ?></td>
                                    <td><?php echo $sucursal->direccion; ?></td>
                                    <td><?php echo $sucursal->ciudad; ?></td>
                                    <td><?php echo $sucursal->celular; ?></td>
                                    <td><?php echo $sucursal->telefono; ?></td>
                                    <td><?php echo $sucursal->fax; ?></td>
                                    <td>
                                        <?php echo MkcHtml::buttonTable('Modificar sucursal', "config/sucursal/editar/$key_upd/", null, 'info', 'edit'); ?>
                                        <?php echo MkcHtml::buttonTable('Eliminar sucursal', "config/sucursal/eliminar/$key_del/", array('class'=>'js-confirm', 'confirm-title'=>'Eliminar sucursal', 'confirm-body'=>'Está seguro de eliminar esta sucursal? <br />Recuerda que esta operación no se puede reversar.'), 'danger', 'trash'); ?>
                                    </td>
                                </tr>
                                <?php $sucursal->counter++; ?>
                            <?php endforeach; ?>
                        </tbody>
                    </table>

                </div>
            </div>
                <div class="box-footer">
                    <?php View::partial('paginators/default', false, array('page'=>$sucursales, 'url'=>"config/sucursal/listar/$order/")); ?>
                </div>

        </div>
    </div>
</section>