<div class="pull-right hidden-xs">
    <p>Versión: <?php echo APP_VERSION; ?> - Ip: <?php echo Session::has('ip') ? Session::get('ip') : MkcUtils::getIp(); ?> - Tiempo: <?php echo number_format(round((microtime(1)-START_TIME),4),4),' seg.'?></p>
</div>
<div>
    <p>&copy; Copyright <?php echo date("Y"); ?> - <?php echo MkcHtml::outLink('http://www.dailyscript.com.co/', 'Dailyscript', array('target'=>'_blank')); ?>. Todos los derechos reservados. <?php echo MkcHtml::outLink('http://www.dailyscript.com.co/contacto/', 'Contacto', array('target'=>'_blank')); ?></p>
</div>
