<div class="main-nav-wrapper hidden-phone hidden-tablet">
    <div class="navbar navbar-fixed-top main-nav">
        <div class="navbar-inner">
            <div class="container-fluid ">                        
                <div class="nav-collapse">
                    <?php echo MkcMenu::desktop(); ?>
                </div>
            </div>                    
        </div>
    </div> 
    <?php echo MkcMenu::getItems(); ?>                       
</div>
