<?php View::notify(); ?>

<div class="container-fluid mkc-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <div class="mkc-overflow">

        <?php echo MkcForm::open('', 'post', array('id'=>'form', 'class'=>'mkc-validate')); ?>

        <div class="row-fluid">
            <div class="span12">
                <?php echo MkcForm::textarea('estado_usuario.descripcion', array('class'=>'input-xxlarge input-required mask-text show-error'), NULL, 'Motivo del cambio de estado'); ?>
            </div>
        </div>

        <div class="row-fluid">
            <div class="form-actions">
                <?php echo MkcButton::save('Actualizar estado'); ?>
                <?php echo MkcButton::reset('form'); ?>
                <?php echo MkcButton::cancel(); ?>
            </div>
        </div>

        <?php echo MkcForm::close(); ?>

    </div>

</div>
