<?php View::notify(); ?>

<div class="container-fluid mkc-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <div class="btn-toolbar btn-toolbar-top">
        <div class="btn-actions">
            <?php echo MkcHtml::button("sistema/configuracion/", 'basic', array('class'=>'btn-success'), 'asterisk', APP_AJAX); ?>
            <?php echo MkcHtml::button("sistema/configuracion/routes/", 'routes', array('class'=>'btn-warning'), 'random', APP_AJAX); ?>
            <?php echo MkcHtml::button("sistema/configuracion/databases/", 'databases', array('class'=>'btn-warning active'), 'hdd', APP_AJAX); ?>
            <div class="pull-right">
                <?php echo MkcHtml::button("sistema/configuracion/reset/", 'reset', array('class'=>'btn-danger js-confirm', 'confirm-title'=>'Restarurar archivos de configuración', 'confirm-body'=>'Está seguro de querer restastaurar los archivos de configuración? <br />Recuerda que esta operación no se puede reversar.'), 'warning-sign', APP_AJAX); ?>
            </div>
        </div>
    </div>

    <?php echo MkcForm::open('', 'post', array('id'=>'form', 'class'=>'mkc-validate', 'style-form'=>'form-horizontal')); ?>

        <div class="row-fluid">

            <div class="span1">&nbsp;</div>

            <div class="span4">
                <?php echo MkcForm::fieldset('Configuración en desarrollo'); ?>
                    <?php echo MkcForm::text('development.host', array('class'=>'input-required show-error'), $databases['development']['host'], 'Dirección del servidor:', 'Ej: localhost'); ?>
                    <?php echo MkcForm::text('development.username', array('class'=>'input-required show-error'), $databases['development']['username'], 'Usuario:', 'Ej: usuario'); ?>
                    <?php echo MkcForm::text('development.password', null, $databases['development']['password'], 'Contraseña:', 'Ej: clave'); ?>
                    <?php echo MkcForm::text('development.name', array('class'=>'input-required show-error'), $databases['development']['name'], 'Base de datos:', 'Ej: dailyscript'); ?>
                <?php echo MkcForm::fieldset(); ?>
            </div>

            <div class="span1">&nbsp;</div>

            <div class="span4">
                <?php echo MkcForm::fieldset('Configuración en producción'); ?>
                    <?php echo MkcForm::text('production.host', array('class'=>'input-required show-error'), $databases['production']['host'], 'Dirección del servidor:', 'Ej: dbhost87965 - 25.25.25.9'); ?>
                    <?php echo MkcForm::text('production.username', array('class'=>'input-required show-error'), $databases['production']['username'], 'Usuario:', 'Ej: dbuser8495'); ?>
                    <?php echo MkcForm::text('production.password', null, $databases['production']['password'], 'Contraseña:', 'Ej: m1.c7av3'); ?>
                    <?php echo MkcForm::text('production.name', array('class'=>'input-required show-error'), $databases['production']['name'], 'Base de datos:', 'Ej: dailyscript'); ?>
                <?php echo MkcForm::fieldset(); ?>
            </div>

        </div>

        <div class="row-fluid">
            <div class="form-actions">
                <?php echo MkcHtml::button('#', 'TEST', array('class'=>'no-ajax  btn-primary', 'id'=>'btn-test'), 'ok', FALSE); ?>
                <?php // MkcHtml::button("Verificar configuración", array('class'=>'btn', 'id'=>'btn-test')); ?>
                <?php echo MkcButton::submit('Guardar configuración', 'check'); ?>
                <?php echo MkcButton::cancel(); ?>
            </div>
        </div>


    <?php echo MkcForm::close(); ?>


</div>

<?php echo MkcForm::open('', '', array('id'=>'form-modal', 'class'=>'mkc-validate', 'style'=>'form-horizontal')); ?>
    <div class="modal hide" id="form-add-config">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h3>Agregar variable de configuración</h3>
        </div>
        <div class="modal-body">
            <div class="row">
                <div class="span5">
                    <?php echo MkcForm::text('variable', array('class'=>'input-required show-error'), null, 'Nombre de la variable'); ?>
                </div>
                <div class="span5">
                    <?php echo MkcForm::text('valor', array('class'=>'input-required show-error'), null, 'Valor'); ?>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button class="btn" data-dismiss="modal" aria-hidden="true">Cancelar</button>
            <?php echo MkcForm::submit("Crear", array('class'=>'btn btn-primary')); ?>
        </div>
    </div>
<?php echo MkcForm::close(); ?>

<script type="text/javascript">
    $(function(){
        $("#form-modal").submit(function(){
            if(validForm($(this).attr('name'), false)) {
                variable = $('#variable');
                valor = $("#valor");
                $('<div class="control-group">'+
                '<label for="custom_'+variable.val()+'" class="control-label">'+variable.val()+':<span class="req">*</span></label>'+
                '<div class="controls">'+
                '<input id="custom_'+variable.val()+'" class="field text input-required show-errors" type="text" value="'+valor.val()+'" name="custom['+variable.val()+']">'+
                '<p class="help-block"> </p>'+
                '</div></div>').appendTo('#append-config');
                variable.attr('value', '');
                valor.attr('value', '');
                MkcSpinner('hide');
                $("#form-add-config").modal('hide');
            }
            return false;
        });
    });
    $("#btn-test").on('click', function () {
        var form = $("#form");
        $.post('<?php echo PUBLIC_PATH; ?>sistema/configuracion/test/', form.serialize(), function(data, status) {
            $('#mkc-message').html(data).hide().show('slow');
        });
        return false;
    });
</script>