<?php View::process($page_module, $page_title, $set_title); ?>
<section class="content mkc-shell-view">
    <?php View::notify(); ?>
    <div class="box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title"><?php echo $page_title; ?></h3>
        </div>
        <?php echo MkcForm::open('', 'post', array('id'=>'form', 'class'=>'mkc-validate')); ?> 
        <div class="box-body">
            <div class="row form-group">
                <div class="col-md-6">
                    <?php echo MkcForm::text('perfil.perfil', array('class'=>'form-control input-required mask-alpha show-error'), NULL, 'Perfil'); ?>
                </div>
                <div class="col-md-6">
                    <?php echo MkcForm::text('perfil.plantilla', array('class'=>'form-control mask-alphanum show-error'), NULL, 'Plantilla', 'La plantilla de sebe ubicar dentro la caperta "templates".'); ?>
                </div>
            </div>
        </div>
        <div class="box-footer">
            <div class="row form-group">
                <div class="col-md-12 form-group form-actions text-right">
                    <?php echo MkcButton::save('Guardar perfil'); ?>
                    <?php echo MkcButton::reset('form'); ?>
                    <?php echo MkcButton::cancel('sistema/perfil/listar/'); ?>
                </div>
            </div>
        </div>
        <?php echo MkcForm::close(); ?>
    </div>
</section>
