<?php View::notify(); ?>

<div class="container-fluid mkc-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo MkcForm::open('', 'post', array('id'=>'form', 'class'=>'mkc-validate')); ?>

        <div class="row-fluid">
            <div class="span6">
                <?php echo MkcForm::text('perfil.perfil', array('class'=>'input-required mask-alpha show-error'), NULL, 'Perfil'); ?>
            </div>
            <div class="span6">
                <?php echo MkcForm::text('perfil.plantilla', array('class'=>'mask-alphanum show-error'), NULL, 'Plantilla', 'La plantilla de sebe ubicar dentro la caperta "templates".'); ?>
            </div>
        </div>

        <div class="row-fluid">
            <div class="form-actions">
                <?php echo MkcButton::save('Guardar perfil'); ?>
                <?php echo MkcButton::reset('form'); ?>
                <?php echo MkcButton::cancel('sistema/perfil/listar/'); ?>
            </div>
        </div>

    <?php echo MkcForm::close(); ?>

</div>
